### ISSUE TITLE
dir_img and  dir_mask

### ISSUE THREAD

**Issue by znshi** [yelusaleng/RRU-Net#1]
Hi, in the train.py #131 dir_img = './data/data_{}/train/tam/'.format(dataset)
    dir_mask = './data/data_{}/train/mask/'.format(dataset),  can you tell me the dir_img is the orginal size in CASIA v2 or the size 384*256 in your paper?

tks

**Comment by yelusaleng** [comment]
hi, it is 384 * 256

**Comment by znshi** [comment]
Hi, thank you for replying to me .
but i don't know why the  get_imgs_and_masks function  in the train.py will use to_cropped_imgs? can you tell me ?

**Comment by hao297531173** [comment]
znshi你好，我看了你的主页你是吉林大学的然后研究方向是图像篡改检测，请问可以和你交流一下吗，我导师也是吉林大学篡改方向的，我现在是硕士研究生
