### ISSUE TITLE
image processing

### ISSUE THREAD

**Issue by dan326326** [yelusaleng/RRU-Net#11]
Hi, in your code , you split each image into two parts ,left  and right ,can you tell me why  you do this

# training images are square
    ids = split_ids(get_ids(dir_img)) 
    iddataset = split_train_val(ids, val_percent)  #把分成两部分的图片做成一个列表，按比例分配为（验证集和训练）

**Comment by yelusaleng** [comment]
hi, that is just a data augmentation operation.

**Comment by dan326326** [comment]
thank you!






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月28日(星期二) 晚上6:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yelusaleng/RRU-Net] image processing (#11)





 
hi, that is just a data augmentation operation.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dan326326** [comment]
Hello, may I ask how much GPU memory you have when training? and how many GPU




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月28日(星期二) 晚上6:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yelusaleng/RRU-Net] image processing (#11)





 
hi, that is just a data augmentation operation.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yelusaleng** [comment]
too long ago, i forget it

**Comment by dan326326** [comment]
> too long ago, i forget it

THANK YOU!
