### ISSUE TITLE
dataset processing

### ISSUE THREAD

**Issue by dan326326** [yelusaleng/RRU-Net#16]
Hello,Thank you for your wonderful code！I see COLUMB data set is used in the paper, may I ask how do you deal with the mask of this data set

**Comment by yelusaleng** [comment]
you need to convert the masks to binary masks.

**Comment by dan326326** [comment]
Hello, thank you for your reply, but I'm still a little confused. Is it ok to just convert to binary mask?&nbsp;Do you need any other steps?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yelusaleng/RRU-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 下午3:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yelusaleng/RRU-Net] dataset processing (Issue #16)





 
you need to convert the masks to binary masks.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yelusaleng** [comment]
i just convert it to the binary.

**Comment by dan326326** [comment]
Thank you very much for your reply! So this columb dataset is pretty big, does it need to be 384*256 when trainging

**Comment by yelusaleng** [comment]
sure thing

**Comment by dan326326** [comment]
thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yelusaleng/RRU-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月5日(星期天) 晚上9:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yelusaleng/RRU-Net] dataset processing (Issue #16)





 
sure thing
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by poiing** [comment]
请问一下CASIA1.0和CASIA2.0要怎么训练呢

**Comment by dan326326** [comment]
你把数据格式统一成他要求的格式就行了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月12日(星期天) 下午3:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yelusaleng/RRU-Net] dataset processing (Issue #16)





 
请问一下CASIA1.0和CASIA2.0要怎么训练呢
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by poiing** [comment]
mask和tam文件夹里都放什么呢，哪个是原图哪个是

> 你把数据格式统一成他要求的格式就行了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月12日(星期天) 下午3:33 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [yelusaleng/RRU-Net] dataset processing (Issue #16) 请问一下CASIA1.0和CASIA2.0要怎么训练呢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

这个tam和mask里哪个文件夹是放什么文件呢，原图还是什么图呢要怎么放呢

**Comment by dan326326** [comment]
tam是原图&nbsp; &nbsp;mask 是标签




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月13日(星期一) 上午9:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yelusaleng/RRU-Net] dataset processing (Issue #16)





 
mask和tam文件夹里都放什么呢，哪个是原图哪个是
  
你把数据格式统一成他要求的格式就行了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月12日(星期天) 下午3:33 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [yelusaleng/RRU-Net] dataset processing (Issue #16) 请问一下CASIA1.0和CASIA2.0要怎么训练呢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
这个tam和mask里哪个文件夹是放什么文件呢，原图还是什么图呢要怎么放呢
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by poiing** [comment]
> tam是原图&nbsp; &nbsp;mask 是标签
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年12月13日(星期一) 上午9:48 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [yelusaleng/RRU-Net] dataset processing (Issue #16) mask和tam文件夹里都放什么呢，哪个是原图哪个是 你把数据格式统一成他要求的格式就行了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月12日(星期天) 下午3:33 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [yelusaleng/RRU-Net] dataset processing (Issue #16) 请问一下CASIA1.0和CASIA2.0要怎么训练呢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 这个tam和mask里哪个文件夹是放什么文件呢，原图还是什么图呢要怎么放呢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

非常感谢，还是要再请问一下，原图指的是被修改之后的图像是嘛，标签具体指的是什么呢，困扰了我很长时间了。

**Comment by dan326326** [comment]
篡改图&nbsp; &nbsp;标签是篡改图的二进制掩码




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yelusaleng/RRU-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月13日(星期一) 上午9:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yelusaleng/RRU-Net] dataset processing (Issue #16)





  
tam是原图&nbsp; &nbsp;mask 是标签
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月13日(星期一) 上午9:48 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [yelusaleng/RRU-Net] dataset processing (Issue #16) mask和tam文件夹里都放什么呢，哪个是原图哪个是 你把数据格式统一成他要求的格式就行了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月12日(星期天) 下午3:33 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [yelusaleng/RRU-Net] dataset processing (Issue #16) 请问一下CASIA1.0和CASIA2.0要怎么训练呢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 这个tam和mask里哪个文件夹是放什么文件呢，原图还是什么图呢要怎么放呢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
非常感谢，还是要再请问一下，原图指的是被修改之后的图像是嘛，标签具体指的是什么呢，困扰了我很长时间了。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by poiing** [comment]
> 



> 篡改图&nbsp; &nbsp;标签是篡改图的二进制掩码
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "yelusaleng/RRU-Net" ***@***.***&gt;; 发送时间:&nbsp;2021年12月13日(星期一) 上午9:55 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [yelusaleng/RRU-Net] dataset processing (Issue #16) tam是原图&nbsp; &nbsp;mask 是标签 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月13日(星期一) 上午9:48 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [yelusaleng/RRU-Net] dataset processing (Issue #16) mask和tam文件夹里都放什么呢，哪个是原图哪个是 你把数据格式统一成他要求的格式就行了 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2021年12月12日(星期天) 下午3:33 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [yelusaleng/RRU-Net] dataset processing (Issue #16) 请问一下CASIA1.0和CASIA2.0要怎么训练呢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 这个tam和mask里哪个文件夹是放什么文件呢，原图还是什么图呢要怎么放呢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 非常感谢，还是要再请问一下，原图指的是被修改之后的图像是嘛，标签具体指的是什么呢，困扰了我很长时间了。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

太感谢了！有可能之后还有问题要请教，非常非常感谢！
