### ISSUE TITLE
Pre-training model

### ISSUE THREAD

**Issue by dan326326** [yelusaleng/RRU-Net#17]
Hello, the pre-training model can't be downloaded, can you upload it? Thank you!

**Comment by yelusaleng** [comment]
i can download the model normally. try to change other browsers?

**Comment by dan326326** [comment]
ok  ,thank you!

**Comment by renmengyuan** [comment]
> i can download the model normally. try to change other browsers?

'result/logs/test.pkl
I can not find the model? Could you share it?
