### ISSUE TITLE
authentic image used for train or test

### ISSUE THREAD

**Issue by yannier912** [yelusaleng/RRU-Net#18]
hello!
In your code tam is the manipulated image and mast is the groundtruth.
I have a quession about authentic images, if authentic images used in training model or test?
Thank you very much!

**Comment by yannier912** [comment]
I have got the answer from issue#2. I will close this issue and thank you again.

**Comment by yelusaleng** [comment]
hi，i didn't use authentic images.

shenyanni ***@***.***> 于2022年2月28日周一 15:42写道：
