### ISSUE TITLE
关于训练集和测试集的选择？

### ISSUE THREAD

**Issue by 170744039** [yelusaleng/RRU-Net#23]
尊敬的作者您好，我知道回复问题也可能是一件比较烦人的事情。但是我不得已需要就这个问题请教一下您。在CISIA2.0中有大概一千八百多张拼接篡改，但您并没有全部采用，经过我的实验，选取适合的训练集和测试集对最终的结果有相当大影响。因为我迫切需要复现您的结果，所以我想请教一下您的训练集和测试集是否可以公布，以文本列表的形式也可以，如果有些麻烦，是否可以告诉我您是怎样选取715和这个100张图片的。

**Comment by 170744039** [comment]
补充一下，通过使用您的best_model,在我随机选取的100张测试集上可以达到
acc ：0.94001359
recall ：0.98047918
f1 ：0.95415276
这样非常好的结果，而我训练的结果却只有
f1 ： 0.54
对于您是怎样训练的，我更加好奇了，我是严格按照您的源码进行的训练，这里面应该没有用论文中提到的学习率动态下降。而关于这个最佳模型best_model，我还想多请教一下是否有在整个cisia上进行微调？

**Comment by 170744039** [comment]
非常感谢您的及时回复，对于您提及的这两篇论文我还没有阅读过，可能还是有些疏忽。倒不是非要复现，训练集与测试集的选择无非是想要一个更好的结果，我自己的工作肯定是想要首先和您站在同一个起跑线上才行。如果有完整的，无需择优的数据集肯定是最为简单实用的，这些我可能还没有发言权，我先研读一下您的新工作所采用的方法，看看是否可以重现这个best_model，可能还会有叨扰，我先说声抱歉以及再次感谢您的回复。

**Comment by yelusaleng** [comment]
没事，有问题随时联系
