### ISSUE TITLE
关于训练集

### ISSUE THREAD

**Issue by laichou** [yelusaleng/RRU-Net#24]
您好，现阶段可以发一下数据集吗？因为训练集又是影响性能的关键，而我在处理数据集的时候遇到了很多问题（比如图片增加了4倍，groundtruth是手动增加还是可以通过脚本增加。比如mask的位深度需要是8但是我的是32等等）。望回复!

**Comment by yelusaleng** [comment]
@laichou 你好，可能需要等两天，待我整理好全部项目代码后再上传

**Comment by laichou** [comment]
您好，您训练best_model的数据集上传了吗？是不是数据集上传到您最新的工作的项目代码里了？能附上链接吗？

**Comment by yelusaleng** [comment]
还没，我打算这周内开一个仓库上传项目代码，到时候我想起来了提醒你吧

**Comment by yelusaleng** [comment]
已上传数据和代码至我的另一个仓库https://github.com/yelusaleng/SAN_and_HDU-Net

**Comment by laichou** [comment]
收到，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yelusaleng/RRU-Net"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月31日(星期天) 凌晨0:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yelusaleng/RRU-Net] 关于训练集 (Issue #24)





 
已上传数据和代码至我的另一个仓库https://github.com/yelusaleng/SAN_and_HDU-Net
