### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by Lebenslang** [yelusaleng/RRU-Net#25]
您好，我在使用CASIA2.0的数据训练RRUnet时loss一直上升，且输出结果在一轮训练后全是表示未篡改的全黑图片，训练Unet也是同样的情况，请问您对此有什么建议吗？
![image](https://user-images.githubusercontent.com/44132469/185622018-2ebe3cfb-600c-4e93-8a69-c391212bafc0.png)
![image](https://user-images.githubusercontent.com/44132469/185622163-35919f31-6652-4b01-95e4-8bc26b09aadd.png)

**Comment by yelusaleng** [comment]
这个问题太泛了，我无法给出准确的答案，我的建议是你再仔细检查你的代码

**Comment by Lebenslang** [comment]
好的，感谢您的回复
