### ISSUE TITLE
F1 score

### ISSUE THREAD

**Issue by ahuxjz** [yelusaleng/RRU-Net#3]
hi,How to get f1 score?

**Comment by hao297531173** [comment]
pred->[batch, 1, h, w]
target->[batch, 1, h, w]
acc_mask = torch.mul(pred, target)
pred_sum = torch.sum(pred)
target_sum = torch.sum(target)
precise = acc_mask / pred_sum
recall = acc_mask / target_sum
f1 = 2*precise*recall / (precise + recall)

**Comment by hao297531173** [comment]
你好，请问你的RRUNet里面图像级分类是怎么做的



---Original---

**Comment by yelusaleng** [comment]
这是基于像素的分类，建议能仔细看下原文

hao297531173 <notifications@github.com> 于2020年12月2日周三 上午8:58写道：

**Comment by hao297531173** [comment]
好的，谢谢



---Original---

**Comment by laichou** [comment]
> pred->[batch, 1, h, w] target->[batch, 1, h, w] acc_mask = torch.mul(pred, target) pred_sum = torch.sum(pred) target_sum = torch.sum(target) precise = acc_mask / pred_sum recall = acc_mask / target_sum f1 = 2_precise_recall / (precise + recall)
请问想得到这些评价指标，应该把这些代码具体放在哪里?望回复!

**Comment by laichou** [comment]
@hao297531173 
pred->[batch, 1, h, w]
target->[batch, 1, h, w]
acc_mask = torch.mul(pred, target)
pred_sum = torch.sum(pred)
target_sum = torch.sum(target)
precise = acc_mask / pred_sum
recall = acc_mask / target_sum
f1 = 2preciserecall / (precise + recall)
请问想得到这些评价指标，应该把这些代码具体放在哪里?望回复!
