### ISSUE TITLE
为什么我在服务器上跑出来效果很差啊

### ISSUE THREAD

**Issue by hao297531173** [yelusaleng/RRU-Net#4]
你好，我用代码里面的参数去服务器上跑效果很差，最后网络输出大部分都是背景，请问你知道是为什么吗
![image](https://user-images.githubusercontent.com/38497778/99868046-f60f9700-2bf9-11eb-99c8-25ad68363de8.png)
![image](https://user-images.githubusercontent.com/38497778/99868049-fe67d200-2bf9-11eb-8453-c46a58bd558b.png)
![image](https://user-images.githubusercontent.com/38497778/99868051-03c51c80-2bfa-11eb-9e3a-e9a1de81ca30.png)

**Comment by 85zhanghao** [comment]
请问你是用什么数据集进行训练的呢？
