### ISSUE TITLE
How do you get image-level detection result?

### ISSUE THREAD

**Issue by ilovecv** [yelusaleng/RRU-Net#7]
Hi,

May I know how you get the detection results at image level (Table 3), shown in section 4.2 of your paper? Thank you very much!

**Comment by yelusaleng** [comment]
hi, you can judge whether the image has been tampered by observing whether the detection result contains tampered pixels.

**Comment by ilovecv** [comment]
@yelusaleng If the model is only trained with forged images, then the detection result may have false positives (tampered pixels) for authentic images, too. What do you think? Thanks!

**Comment by yelusaleng** [comment]
sure. 
you should do more experiments to verify your ideas.
